name: build-plugin

on: [push]
jobs:
  check-sdk-version:
    runs-on: ubuntu-latest
    steps:
      - uses: rodrigo-nogues/github-action-install-atlassian-sdk@v1
      - run: atlas-mvn test
